import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import kurtosis, skew
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

#Reads dataset generated by generate_dataset.py which contains 5 dataset columns
df = pd.read_csv("los_nlos_dataset.csv")

def extract_features(row): #Used to calculate 5 scalar features

    # Complex channel taps
    h = np.array([row[f'h_real_{i}'] + 1j*row[f'h_imag_{i}'] for i in range(6)])

    # Tap powers
    power = np.abs(h)**2

    # Delays
    tau = np.array([row[f'tau_{i}'] for i in range(6)])

    # 1. Kurtosis - describes the shape/peakedness of the power distribution
    kurt = kurtosis(power)

    # 2. Skewness - describes the asymmetry of the power distribution.
    skw = skew(power)

    # 3. RMS delay spread - spread of the multipath delays around the mean delay
    mean_delay = np.sum(power*tau) / np.sum(power) # Power-weighted mean delay

    rms_delay = np.sqrt(np.sum(power*(tau-mean_delay)**2) / np.sum(power))

    # 4. Rising time: 10% to 90% cumulative power
    cumulative_power = np.cumsum(power)
    total_power = np.sum(power)

    # First delay at which cumulative power reaches at least 10% of total power
    t10 = tau[np.argmax(cumulative_power >= 0.10*total_power)]

    # First delay where cumulative power reaches at least 90% of total power
    t90 = tau[np.argmax(cumulative_power >= 0.90*total_power)] 

    rising_time = t90 - t10

    # 5. Rician K-factor - how strong the LOS component is compared with the scattered multipath components.
    peak_power = np.max(power)

    K = 10*np.log10(peak_power / (total_power - peak_power + 1e-12))

    return pd.Series([kurt,skw,rising_time,rms_delay,K]) # Returns these five features

#Adds these five features to the dataframe
df[['kurtosis','skewness','rising_time','rms_delay_spread','rician_k']] = df.apply(extract_features, axis=1)

# SNR values in the dataset
SNR_values = [0, 5, 10, 15, 20, 25, 30]

# Feature names
features = ['kurtosis','skewness','rising_time','rms_delay_spread','rician_k']

# Store accuracies
results = []

for snr in SNR_values:

    # Select data for this SNR
    data = df[df['snr_db'] == snr]

    # Input and target
    X = data[features].values
    y = data['label'].values

    # 80% training, 20% testing
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20,random_state=67,stratify=y)

    # Train six SVMs
    accuracies = []

    for feature_set in [['kurtosis'],['skewness'],['rising_time'],['rms_delay_spread'],['rician_k'],features]:

        # Select required features
        Xtr = X_train[:, [features.index(f) for f in feature_set]]
        Xte = X_test[:, [features.index(f) for f in feature_set]]

        # Standardize
        scaler = StandardScaler()

        Xtr = scaler.fit_transform(Xtr)
        Xte = scaler.transform(Xte)

        # Radial Basis Function SVM (allows SVM to create nonlinear decision boundaries) with C = 1
        svm = SVC(kernel='rbf', C=1)
        svm.fit(Xtr, y_train)

        # Prediction
        y_pred = svm.predict(Xte)

        # Accuracy
        accuracy = accuracy_score(y_test, y_pred)
        accuracies.append(accuracy)

        #For SNR = 25dB and at SVM-6, storing the trained SVM model and standardized object
        if snr == 25 and feature_set == features:
            svm6_25 = svm
            scaler6_25 = scaler


    results.append([snr] + accuracies)

# Create result table
results_df = pd.DataFrame(results,columns=['SNR','SVM-1 Kurtosis','SVM-2 Skewness','SVM-3 Rising Time','SVM-4 RMS Delay Spread','SVM-5 Rician K','SVM-6 All Features'])


# Testing the fixed model at every SNR

accuracy_fixed = []

for snr in SNR_values:

    # Select data for this SNR
    data_snr = df[df['snr_db'] == snr]

    # Input and target
    X = data_snr[features].values
    y = data_snr['label'].values

    # Create 80/20 test split for this SNR
    X_train_snr, X_test_snr, y_train_snr, y_test_snr = train_test_split(X,y,test_size=0.20,random_state=67,stratify=y)

    # Use the scaler learned from 25-dB training data
    X_test_snr = scaler6_25.transform(X_test_snr)

    # Use the same SVM trained at 25 dB
    y_pred = svm6_25.predict(X_test_snr)

    # Accuracy
    accuracy = accuracy_score(y_test_snr, y_pred)
    accuracy_fixed.append(accuracy)


# Results

results_fixed = pd.DataFrame({'SNR (dB)': SNR_values,'Fixed SVM-6 Accuracy (%)':np.array(accuracy_fixed) * 100})

print(results_df.to_string(index=False))
print("\n")
print(results_fixed)

plt.figure(figsize=(10, 6)) # Plotting a figure

# Plotting SVM trained using Kurtosis
plt.plot(results_df['SNR'], results_df['SVM-1 Kurtosis'] * 100,'o-', label='SVM-1: Kurtosis')

# Plotting SVM trained using Skewness
plt.plot(results_df['SNR'], results_df['SVM-2 Skewness'] * 100,'s-', label='SVM-2: Skewness')

# Plotting SVM trained using Rising Time
plt.plot(results_df['SNR'], results_df['SVM-3 Rising Time'] * 100,'^-', label='SVM-3: Rising Time')

# Plotting SVM trained using RMS Delay Spread
plt.plot(results_df['SNR'], results_df['SVM-4 RMS Delay Spread'] * 100,'d-', label='SVM-4: RMS Delay Spread')

# Plotting SVM trained using Rician K-factor
plt.plot(results_df['SNR'], results_df['SVM-5 Rician K'] * 100,'x-', label='SVM-5: Rician K-factor')

# Plotting SVM trained using all five features
plt.plot(results_df['SNR'], results_df['SVM-6 All Features'] * 100,'*-', label='SVM-6: All Features')

plt.xlabel('SNR (dB)') # Title for x-axis
plt.ylabel('Classification Accuracy (%)') # Title for y-axis
plt.title('SVM Classification Accuracy vs SNR') # Title for plot

plt.xticks(results_df['SNR']) # Sets the position of SNR values on the x-axis
plt.ylim(0, 105) # Keep the y-axis between 0 and 105

plt.grid(True) # Enables the grid
plt.legend() # Differentiates between diffrerent SVMs
plt.tight_layout() # Automatically adjusts the spacing in plot


plt.figure(figsize=(9,6)) # Plotting a figure

# Trained and tested at the same SNR
plt.plot(results_df['SNR'],results_df['SVM-6 All Features'] * 100,'o-',label='Train = Test SNR')

# Fixed model: Trained only at 25 dB
plt.plot(results_fixed['SNR (dB)'],results_fixed['Fixed SVM-6 Accuracy (%)'],'s-',label='Train at 25 dB')

plt.xlabel('SNR (dB)') # Title for x-axis
plt.ylabel('Classification Accuracy (%)') # Title for y-axis
plt.title('SVM-6 Classification Accuracy vs SNR') # Title for plot

plt.xticks([0, 5, 10, 15, 20, 25, 30]) # Sets the position SNR values on the x-axis
plt.ylim(0, 105) # Keep the y-axis between 0 and 105

plt.grid(True) # Enables the grid
plt.legend() # Differentiates between diffrerent classification accuracies
plt.tight_layout() # Automatically adjusts the spacing in plot
plt.show() # Plotting figure 1

plt.show() # Plotting figure 2
